-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeKScCESOykNipywS
8kdhC+GSYx/Ep1kz0VB70gdS+i+gCgYIKoZIzj0DAQehRANCAAQtXUS73t5IoBsn
ToGfX/K/IGOXq9PB7piQcbcdLUDU5zvDosePacNck2n2zQPW803/ab0JFlHjqgHC
TTInm9RS
-----END PRIVATE KEY-----